#!/bin/bash
#PBS -S /bin/bash
#PBS -q normalq
#PBS -l nodes=2:ppn=360
#PBS -l walltime=04:00:00
#PBS -M pasfielt@my.erau.edu 
#PBS -m bea
#PBS -n 
#PBS -N Regularization_Deblurring_Pasfield
#PBS -d /scratch/pasfielt/deblurring/
# PBS <-- This is a comment, note the whitespace

### cd to directory where the job was submitted:
cd "${PBS_O_WORKDIR}"

# load the required environment modules 
#module load openmpi/gcc/64/1.10.3 
module load gcc/8.5.0
module load python/3.11.7
module load openmpi/5.0.2
module load py-pip
module load py-numpy
module load py-cython
pip install --upgrade --proxy http://dbproxy.erau.edu:3128/ --user scipy
module load py-packaging py-setuptools py-utils

pip install --proxy http://dbproxy.erau.edu:3128/ --user -r requirements.txt



### run the program (on the nodes as provided by PBS):

date
mpirun -n 360 python cleaned_code.py
date

###############################################################################
